St2 update

diff --git a/fenics.install b/fenics.install
--- a/fenics.install
+++ b/fenics.install
@@ -1,109 +1,147 @@
+#!/bin/bash
+
+if [ $# -ne 2 ] ; then
+  echo "Usage: $0 INSTALLATION logdir"
+  exit 1
+fi
+
+INSTALLATION=$1
+logdir=$2
+
+##
+## are we in the right location?
+##
+if [ ! -d fiat ] ; then
+  echo "Cannot find fiat directory: we are probably not in the right location"
+  exit 1
+fi
+
+#module load gcc
+#module load intel 
+
+# add a missing ply module
+#export PYTHONPATH=${HOME}/.local/lib/python3.6/site-packages:${PYTHONPATH}
+export EXTRA_PYTHONPATH=
+
+rm -f $logdir/install.log
+
 #
 # bunch of pip-based installs
 #
-module list
-export PIP=pip3
-export PIP_OPTION=--install-option
-export PYTHON_VERSION=3.6
+export INSTALL_DIR=${INSTALLATION}/fiat
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE Fiat install" ; echo ; \
+  cd fiat    && pip3 install --install="--prefix=${INSTALL_DIR}" . ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 
-mkdir -p ${FENICS_DIR}/python
-( pip3 install --prefix=${FENICS_DIR}/python ply )
-export PYTHONPATH=$PYTHONPATH:${FENICS_DIR}/python/lib/python${PYTHON_VERSION}/site-packages
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${FENICS_DIR}/python/lib/python${PYTHON_VERSION}/site-packages
-export PY_PLY_PATH=${FENICS_DIR}/python/lib/python${PYTHON_VERSION}/site-packages
-export PY_PLY_path=${FENICS_DIR}/python/lib/python${PYTHON_VERSION}/site-packages
+export INSTALL_DIR=${INSTALLATION}/instant
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE Instant install" ; echo ; \
+  cd instant && pip3 install --install="--prefix=${INSTALL_DIR}" . ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 
-export PKG_INSTALL_DIR=${FENICS_DIR}/fiat
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-( echo ; echo "Fiat install in ${PKG_INSTALL_DIR}" ; echo ; \
-  cd fiat    && ${PIP} install ${PIP_OPTION}="--prefix=${PKG_INSTALL_DIR}" . )
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
+export INSTALL_DIR=${INSTALLATION}/dijitso
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE Dijitso install" ; echo ; \
+  cd dijitso && pip3 install --install="--prefix=${INSTALL_DIR}" . ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 
-export PKG_INSTALL_DIR=${FENICS_DIR}/instant
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-( echo ; echo "Instant install in ${PKG_INSTALL_DIR}" ; echo ; \
-  cd instant && ${PIP} install ${PIP_OPTION}="--prefix=${PKG_INSTALL_DIR}" . ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
+export INSTALL_DIR=${INSTALLATION}/ufl
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE UFL install" ; echo ; \
+  cd ufl     && pip3 install --install="--prefix=${INSTALL_DIR}" . ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 
-export PKG_INSTALL_DIR=${FENICS_DIR}/dijitso
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-( echo ; echo "Dijitso install in ${PKG_INSTALL_DIR}" ; echo ; \
-  cd dijitso && ${PIP} install ${PIP_OPTION}="--prefix=${PKG_INSTALL_DIR}" . ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-
-export PKG_INSTALL_DIR=${FENICS_DIR}/ufl
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-( echo ; echo "UFL install in ${PKG_INSTALL_DIR}" ; echo ; \
-  cd ufl     && ${PIP} install ${PIP_OPTION}="--prefix=${PKG_INSTALL_DIR}" . ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-
-export PKG_INSTALL_DIR=${FENICS_DIR}/ffc
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-( echo ; echo "FFC install in ${PKG_INSTALL_DIR}" ; echo ; \
-  cd ffc     && ${PIP} install ${PIP_OPTION}="--prefix=${PKG_INSTALL_DIR}" . ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
+export INSTALL_DIR=${INSTALLATION}/ffc
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE FFC install" ; echo ; \
+  cd ffc     && pip3 install --install="--prefix=${INSTALL_DIR}" . ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 
 #
-# the next three are cmake-based
+# the next two are cmake-based
 #
-export cmake_flags="-DCMAKE_CXX_COMPILER=${FENICS_X_COMPILER} -DCMAKE_C_COMPILER=${FENICS_C_COMPILER}"
+#export cmake_flags="-DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc"
 export BOOST_ROOT=${TACC_BOOST_DIR}
 
-export PKG_INSTALL_DIR=${FENICS_DIR}/eigen
-export EIGEN_INSTALL_DIR=${FENICS_DIR}/eigen
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-export PKG_BUILD_DIR=${BUILD_DIR}/eigen-build
-rm -rf ${PKG_BUILD_DIR}
-mkdir -p ${PKG_BUILD_DIR}
-( echo ; echo "Eigen install in ${PKG_INSTALL_DIR}" ; echo \
-  && cd ${PKG_BUILD_DIR} \
-  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${PKG_INSTALL_DIR} \
-        ${cmake_flags} ${SRC_DIR}/eigen \
-  && make && make install ) 
-export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${PKG_INSTALL_DIR}
-
-export PKG_INSTALL_DIR=${FENICS_DIR}/dolfin
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-export PKG_BUILD_DIR=${BUILD_DIR}/dolfin-build
-rm -rf ${PKG_BUILD_DIR}
-mkdir -p ${PKG_BUILD_DIR}
-( echo ; echo "Dolfin install in ${PKG_INSTALL_DIR}" ; echo \
-  && cd ${PKG_BUILD_DIR} \
-  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${PKG_INSTALL_DIR} \
-        -D CMAKE_CXX_COMPILER:FILEPATH=mpicxx \
+export INSTALL_DIR=${INSTALLATION}/eigen
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE Eigen install" ; echo \
+  && rm -rf eigen-build && mkdir -p eigen-build && cd eigen-build \
+  && export CXX=`which mpicxx` && export CC=`which mpicc` \
+  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
         -D CMAKE_C_COMPILER:FILEPATH=mpicc \
+        -D CMAKE_CXX_COMPILER:FILEPATH=mpicxx \
+        -D CMAKE_Fortran_COMPILER:FILEPATH=mpif90 \
+        ${cmake_flags} ../eigen \
+  && make install ) \
+    2>&1 | tee -a $logdir/install.log
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
+
+export INSTALL_DIR=${INSTALLATION}/dolfin
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+( echo ; echo "VLE Dolfin install" ; echo \
+  && ( cd dolfin && git clean -fdx ) \
+  && rm -rf dolfin-build && mkdir -p dolfin-build && cd dolfin-build \
+  && export CXX=`which mpicxx` && export CC=`which mpicc` \
+  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
+        -D CMAKE_C_COMPILER:FILEPATH=mpicc \
+        -D CMAKE_CXX_COMPILER:FILEPATH=mpicxx \
         -D CMAKE_Fortran_COMPILER:FILEPATH=mpif90 \
         -D DOLFIN_AUTO_DETECT_MPI=false \
-        -D EIGEN3_INCLUDE_DIR=${EIGEN_INSTALL_DIR}/include/eigen3 \
-        ${cmake_flags} ${SRC_DIR}/dolfin \
-  && make && make install ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${PKG_INSTALL_DIR}
+        -D EIGEN_DIR=${INSTALLATION}/eigen \
+        -D EIGEN3_INCLUDE_DIR=${INSTALLATION}/eigen/include/eigen3 \
+        ${cmake_flags} ../dolfin \
+  && make VERBOSE=1 && make install ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALLATION}/dolfin/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALLATION}/dolfin/lib/python3.6/site-packages/
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
+export CMAKE_PREFIX_PATH=${INSTALL_DIR}:${CMAKE_PREFIX_PATH}
 
-export PKG_INSTALL_DIR=${FENICS_DIR}/mshr
-rm -rf ${PKG_INSTALL_DIR}
-mkdir -p ${PKG_INSTALL_DIR}
-export PKG_BUILD_DIR=${BUILD_DIR}/mshr-build
-rm -rf ${PKG_BUILD_DIR}
-mkdir -p ${PKG_BUILD_DIR}
-echo ; echo "Mshr install in ${PKG_INSTALL_DIR}" ; echo
+export nocmake="\
+        -D DOLFIN_ENABLE_MPI=true \
+    "
+#  && sed -i s?/opt/intel/compilers_and_libraries_2017.4.196/linux/bin/intel64/icpc?mpicxx? CMakeCache.txt
+#if (DOLFIN_ENABLE_MPI)
+#if (DOLFIN_AUTO_DETECT_MPI)
+#else
+
+echo ; echo "VLE Mshr install" ; echo
+export INSTALL_DIR=${INSTALLATION}/mshr
+rm -rf ${INSTALL_DIR} && mkdir -p ${INSTALL_DIR}
+export CMAKE_MODULE_PATH=${INSTALL_DIR}:${CMAKE_MODULE_PATH}
 ( cd mshr \
-  && cd ${PKG_BUILD_DIR} \
-  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${PKG_INSTALL_DIR} \
-           ${cmake_flags} ${SRC_DIR}/mshr \
-  && make && make install ) 
-export PYTHONPATH=$PYTHONPATH:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
-export PYTHON_EXTRA_PATHS=${PYTHON_EXTRA_PATHS}:${PKG_INSTALL_DIR}/lib/python${PYTHON_VERSION}/site-packages/
+  && rm -rf build && mkdir -p build && cd build \
+  && cmake -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
+        -D CMAKE_C_COMPILER:FILEPATH=mpicc \
+        -D CMAKE_CXX_COMPILER:FILEPATH=mpicxx \
+        {cmake_flags} .. \
+  && make VERBOSE=1 && make install ) \
+    2>&1 | tee -a $logdir/install.log
+export PYTHONPATH=$PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+export EXTRA_PYTHONPATH=$EXTRA_PYTHONPATH:${INSTALL_DIR}/lib/python3.6/site-packages/
+
+echo ${EXTRA_PYTHONPATH} > $logdir/fenics.pythonpath
+
+# chmod -R o+rX ${FENICS_DIR}
+
+  #VLE Add the installation prefix of "DOLFIN" to CMAKE_PREFIX_PATH or set
+  #VLE "DOLFIN_DIR" to a directory containing one of the above files.  If "DOLFIN"
+  #VLE provides a separate development package or SDK, be sure it has been
+  #VLE installed.
